version: '3.2'

services:
  app: &app
    image: node:16
    command: echo "disabled by default"
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      default:
      internal:
    user: 1000:1000

  server:
    <<: *app
    command: npm run dev
    ports:
      - 3000:3000

  test:
    <<: *app
    environment:
      - NODE_ENV=test

  postgres:
    image: postgres:14.3
    ports:
      - 5432:5432
    volumes:
      - development_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  elasticsearch:
    deploy:
      replicas: 0
    image: elasticsearch:8.2.2
    ports:
      - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - node.name=elastic
      - cluster.name=elastic-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.host=0.0.0.0
      - http.port=9200
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  development_data:
  es_data:

networks:
  internal:
