version: '3.2'

services:
  app: &app
    image: node:16
    command: echo "disabled by default"
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - postgres
    user: 1000:1000

  server:
    <<: *app
    command: npm run dev
    ports:
      - 3000:3000

  test:
    <<: *app
    environment:
      - NODE_ENV=test

  postgres:
    image: postgres:14.3
    ports:
      - 5432:5432
    volumes:
      - development_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

volumes:
  development_data:
